services:
  portal-pirata:
    build:
      context: .
    ports:
      - "4173:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./sw.js:/usr/share/nginx/html/sw.js:ro
      - ./src:/usr/share/nginx/html/src:ro
    restart: unless-stopped
